export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_TO_VIEWED_ITEMS = 'ADD_TO_VIEWED_ITEMS';
export const INCREASE = 'INCREASE';
